version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: drf_homework
      POSTGRES_USER: drf_user
      POSTGRES_PASSWORD: drf_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=drf_homework
      - DJANGO_DB_USER=drf_user
      - DJANGO_DB_PASSWORD=drf_password
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery:
    build: .
    command: celery -A DRF_homework worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=drf_homework
      - DJANGO_DB_USER=drf_user
      - DJANGO_DB_PASSWORD=drf_password
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A DRF_homework beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=drf_homework
      - DJANGO_DB_USER=drf_user
      - DJANGO_DB_PASSWORD=drf_password
      - CELERY_BROKER_URL=redis://redis:6379/0

volumes:
  postgres_data: 